[server]
bind-address=":8080"
mode="release"
rollbar-token=""
rollbar-environment=""

[mdb]
url=""

[elasticsearch]
url="http://elastic:9200"
cdn-url="http://cdn.archive"
unzip-url="http://nginx/assets/api"
data-folder="/app/data"
sources-folder="/assets/sources"
prepare-docs-batch-size=20
prepare-docs-parallelism=2
timeout-for-highlight="4s"
check-typo=true

[file_service]
url1="http://files.archive"

[assets_service]
url="http://nginx/assets/api/"

[cache]
refresh-search-stats="60s"
