[mdb]
url=""

[server]
bind-address=":8081"
mode="release"
rollbar-token=""
rollbar-environment=""
base-url="http://cdn.archive/"

[file_service]
urls=[
  "http://files.archive/api/v1/get"
]

[permissions]
public-only=true