[server]
bind-address="127.0.0.1:8084"
mode="release"
rollbar-token=""
rollbar-environment=""
log="./logs/mdb.log"
docs="./docs.html"

[mdb]
url="postgres://localhost/mdb?sslmode=disable"

[events]
handlers=["logger"]
emitter-size=1024

[authentication]
enable=false
issuer=""

[permissions]
enable=false
log=false
